name: Build and Release Chrome Extension

on:
  push:
    tags:
      - "v*" # This triggers the workflow on version tags like v1.0, v1.1, etc.

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build # This runs your build command, ensure it's in your package.json

      - name: Prepare extension package
        run: |
          mkdir -p manganato-enhancer
          cp -r dist manganato-enhancer/
          cp manifest.json manganato-enhancer/
          cd manganato-enhancer && zip -r ../manganato-enhancer.zip *

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: manganato-enhancer.zip # The ZIP file created in the previous step
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: "Automated release of the Chrome extension."
